### ISSUE TITLE
Second "good" results

### ISSUE THREAD

**Issue by Akababa** [Zeta36/chess-alpha-zero#37]
By training the model with a similar config as in this repo (7 residual blocks of 256 depth) on FICS games, I think it's not doing too bad: (I played white, model gets 1200 sims/move)

![image](https://camo.githubusercontent.com/6b8a4767948a4766a70fd21364a75a2f30ee1026/68747470733a2f2f692e696d6775722e636f6d2f677767487262672e676966)

The model and weights are in [my fork](https://github.com/Akababa/chess-alpha-zero), please feel free to clone and try for yourself (It's not compatible with this repo)

What are everyone's thoughts on this? Should I keep training this or start to scale up to more blocks? There are a total of 7*2+1=15 convolutions now, barely enough to traverse the board and back, so this might be a problem with respect to long-range tactics.

**Comment by Zeta36** [comment]
It looks very promising!! Please stay training for a while so we can check if the model is able to finish a gane without blunder!!

**Comment by Akababa** [comment]
Thanks for the encouragement! The tactics is a worry but at least it's fun to play with (very aggressive lol). 

What do you think of the idea of adding "knight-shaped" and "queen-shaped" convolutions? Is it too much "cheating"?

**Comment by Zeta36** [comment]
@Akababa Do you mind if I copy your results into my repository?

**Comment by Akababa** [comment]
Sure, go for it! :)

I'll continue experimenting with 5x5 convolutions, tell me if you have any thoughts on this.

**Comment by Zeta36** [comment]
@Akababa, please can you make me over here a little resume of your improvements and main diferencies against my current master branch in order to mention it in the readme section? Changes in model feed input (the planes you use, etc.), in the workers and so on.

Thank you!!

**Comment by Akababa** [comment]
Sure, I put it on my [wiki ](https://github.com/Akababa/Chess-Zero/wiki)to make it easier to update in the future.

**Comment by Akababa** [comment]
I had some better results today, although I don't think it can get much better in its current form.

![apronusdiagram1514071757](https://user-images.githubusercontent.com/4205182/34323276-ecd2a7b6-e806-11e7-856a-4e2394bd75df.gif)

**Comment by ako1983** [comment]
Who's white?

Sent from my Verizon 4G LTE Droid
On Dec 23, 2017 6:31 PM, Michael Pang <notifications@github.com> wrote:

I had some better results today, although I don't think it can get much better in its current form.

[apronusdiagram1514071757]<https://secure-web.cisco.com/1PTfUVHbV28XFEVn0_kOXqaDQb7Tua92edI1IelXsB_3F7YJD1AP9sSRKK59drEYUYbyOtpqRsLrHM-7PyxMjtttBID6DsUcY00Q4tKgfr1FQYsVbaioxlSABjjCBEFZ8ckO8_K0VHfSV0JWZjdv6oIJLdj1SL9lZDA791-D-mQkkMh3A1yvFZg1DTxg_0FA6OM5_g-GvaBVw2rlrHeXHCWzo1hX0jweRHJX2f96q0JDmtNhv9_kPDgyBZnj15TvMsfUXtQKr-W8VtfaOXuZUI5G80wIIOChceFdyZya06lXvKRSvwsnPDzFv4GlPsh1YfP4P14QfTT4DrfRZsIg1KOxoV56ccbZv_CR2HlwfoPdldBUx4xzci1l0mOWSWVE3/https%3A%2F%2Fuser-images.githubusercontent.com%2F4205182%2F34323276-ecd2a7b6-e806-11e7-856a-4e2394bd75df.gif>

**Comment by Akababa** [comment]
@ako1983 Lol, I'm playing white. Is my chess ability really that bad? :)

**Comment by ako1983** [comment]
No, you crashed it very nice! What is the rating of the engine?

Sent from my Verizon 4G LTE Droid
On Dec 23, 2017 10:24 PM, Michael Pang <notifications@github.com> wrote:

@ako1983<https://secure-web.cisco.com/1nF8I0IKzUg1aZi47T10gEIJsEZX7pHlyEkX95RlVh5mCt1_tax1dBjKB_ejJaGXvF7TTyZumG0LwGq4Gd3lm4Tzb-ZjSHOJf0Qwz6ZVdQPGDGS18DzY8nZEpZnryoEE94T267USwYB5KxWOMHLPX2NQR7l9MeOu0Zf774QIr_Z-gSoPW_c6NHCqwET6rrLjIJYIZdHUNxx02-_tahPZPzX3kWvtuTEl8rciWk2hf4aTyUcoIKt7UO2Yr1M7rHqE2WABqhtlG0FRs7Oi7amJDWfeMIWh7UB1vf2Ta_zKN1IDlUmX62BkXoCrFft82eCYJ55lVPVkI4RUi9hpl7_KsgpdYkS-uBahZg1rnylZELx6osHZMbokXy7Upo9AFZ_3bDlA2wX5hcYMX8K7_W6CQVK8f6Wg6c0RVAn6QgyYFPoox-8dgKv0RnXIbx5QI2ef7/https%3A%2F%2Fgithub.com%2Fako1983> Lol, I'm playing white. Is my chess ability really that bad? :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1M-L-YkvZEtblJRx6ftH6bhOfjmsAmisGCac_GtMZ2itAUmhgYReTai2D_Qepxezkz2KSc6dr--gOEuKBV-xWpCmQRrRV_y1o0HD66h4e0A1lVLCKfWv4HFFYE3-q5dtR_qj1KidzeutrM-1cCHLgqPFFCwRIPMOEnrpPIingzs2WSve4ba_3jDsy1TapAwhRGL9FQjJBbuflCOKqZyI8GLMHqnnSS2GYnfes5jgBto29NkMtJg4ln3dm9IOwCZBW5b2i3GeYrIb08264RYpgZ-CosAn_mykcuygiOaSXLiItZU4skd1gbGCwfvXESDDSeicPy95DSGBeNyFRK0Fc6qM-zBcRDEZ146Tj-kFdCjVQllVCo21h9uLxtleFDea5kDuFWcSqZ-HV-TIxoUz2i4bbdyd8qo48Btq5CkdWTJXiKtnik_tLiZWfQGVF4eJ9/https%3A%2F%2Fgithub.com%2FZeta36%2Fchess-alpha-zero%2Fissues%2F37%23issuecomment-353763007>, or mute the thread<https://secure-web.cisco.com/1mqS9RsO2zPs4OEB7W2E7M9g-WtuK8s4h_g6nuzW2OlRgjW4beMOmvsHWI-gAw3tU19I99Zz3A34nDmM3ODTuKgtnWRrUnvBfVNUJH3fdpXE5mNfhTGExdUBiI6kVLzUk01NlXpbXNbylRG7CiQN3oTjon-6fSoBK2ir6KeL-V1Kplgn!
%20RfQfY5cd_WA8nvcw1aqP4sl1OPKV83Vs_GZrSZm1SJjxSt7r4QQ8_h8-4Byqc1EGQomNKzjIpaXSbcD2bsmfJftNjklq8IcQLLhkdzTGmRKawANbGkUoBJOrpbyDrA0mfQG10oLqjRidC4BffrVHkr62CfHrqQoWfSPm_WpFqfHlaebYEuxnI0BiHwG1ycxV6sN9N3RxJC5oVC7ISL4IzUCVKqiWqLtDaPBQFiYbUgawXIcieSfwupM0TCa4EZHeEoluA3iCvMyom6dOE/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJmd3GF1OygVhv-h_9Amtu1EgrGhtHknks5tDcPpgaJpZM4RLSYA>.

**Comment by Akababa** [comment]
I guess around 1300 for now. I want to try out different architectures but training on my laptop is very slow!

**Comment by Zeta36** [comment]
@Akababa, your result is really promising. Anyway I tried yesterday to run your code (nohistory branch) in my local machine (windows 10) but the 'uci.py' file got stalled and no move were never done. Do you know what can be the problem?

**Comment by Zeta36** [comment]
I'd like also to know how many iterations did you train that model. What was the loss you reached? Did you train with a fixed SL number of files or did you left the SL worker active and changing constantly the playdata files?

About the limitations of the current model, maybe you could try with a higher "res_layer_num" in the configuration (I think DeepMind used 19).

**Comment by Zeta36** [comment]
I created a new branch with your code (nohistory branch), @Akababa. Unfortunately I cannot merge it since I'm having some troubles with the 'sl' worker:

```
2017-12-24 09:23:32,822@chess.pgn ERROR # error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\Samu\Anaconda3\lib\site-packages\chess\pgn.py", line 965, in read_game
    move = board_stack[-1].parse_san(token)
  File "C:\Users\Samu\Anaconda3\lib\site-packages\chess\__init__.py", line 2595, in parse_san
    raise ValueError("illegal san: {0} in {1}".format(repr(san), self.fen()))
ValueError: illegal san: 'h6' in 3rr1k1/p1pq1ppp/Npn3b1/8/3PnQ2/P4PN1/BP4PP/2R2RK1 w - - 4 23
```

Moreover, the 'self' worker is getting stalled for me and the best model you uploaded to your branch after playing with it in Arena is not so good as I thought :(. It still blunders a lot.

If you want to make any change in the branch or upload new weights you are really welcome. As soon as I can see all perfectly working and with a model able not to blunder so much I will merge into master.

Thank you for your work.

**Comment by Zeta36** [comment]
Reviewing the model you uploaded I've found it plays really well. It's a big improvement with respect we've reached until now. If you please can take a look into the branch I created: "akababa-changes" and let it working fine 'sl' and 'self' workers I'll merge automatically :).

**Comment by Akababa** [comment]
Thanks for the code review @Zeta36!

Could you please post the pgn file which is giving you that error with SL? And that looks like maybe a pgn fomat error or chess.pgn bug.

What is the specific error with "self" worker?

**Comment by Akababa** [comment]
About the supervised training: I trained with a total of 20-30,000 games from the FICS 2011-2016 database which ended in checkmate, although it's hard to say for sure because I was constantly changing the model and training weights, and fixed some bugs along the way.

**Comment by ako1983** [comment]
Can't we train it with just a data set from 1850-1900?
Or with just one specific player, let say Andersson and let that play with another model trained by let say Zukretorrt and see the results,
In this way we can move along with history of chess,

Sent from my Verizon 4G LTE Droid
On Dec 24, 2017 11:51 AM, Michael Pang <notifications@github.com> wrote:

About the supervised training: I trained with a total of 20-30,000 games from the FICS 2011-2016 database which ended in checkmate, although it's hard to say for sure because I was constantly changing the model and training weights, and fixed some bugs along the way.

**Comment by Zeta36** [comment]
@Akababa, I merged into master your branch. Can you please check all is working right checking out from master? I cleaned up a little your code and I'd like you to check 'uci', 'self' and 'sl' workers are working normally in your local machine.

Thank you!!

**Comment by Akababa** [comment]
Awesome! I'll do that asap. I assume you got it working on your machine?

**Comment by Zeta36** [comment]
yes, but I want you please to review it. And please if you have better weights upload them :).

**Comment by Akababa** [comment]
![apronusdiagram1514178207](https://user-images.githubusercontent.com/4205182/34333105-ada817c6-e8fe-11e7-8c01-5958aaf264c1.gif)

Lol, I just lost (as black). It's mostly my fault but still not a bad sign I guess.

**Comment by Zeta36** [comment]
@Akababa, white plays very well. It's the weights of the model of that game the one you uploaded on the repo or it's another version more advanced?

**Comment by Akababa** [comment]
It's the same one except with virtual loss set to 2. I still wasn't able to improve on that with my 2 GB GPU :(
